controller:
  type: daemonset

  tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

alloy:
  configMap:
    create: false
    name: alloy-config-kubernetes-suffatech
    key: config.alloy

  mounts:
    varlog: true
  
  extraEnv:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName 