# Varsayılan replika sayısı
replicaCount: 1

image:
  repository: "" # Servis values dosyasından ezilecek (Örn: <NEXUS_PRIVATE_IP>:8083/bot-server)
  pullPolicy: IfNotPresent
  tag: "" # Jenkins CI tarafından üretilen imaj tag'i gelecek

# VSO tarafından suffatech namespace'ine senkronize edilen Nexus pull secret
imagePullSecrets:
  - name: nexus-pull-secret

nameOverride: ""
fullnameOverride: ""

# Pod ve Konteyner Güvenlik Sıkılaştırması (Zero-Trust)
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ortam değişkenleri (Statik veya VSO ile üretilen K8s Secret'larından)
env: []
# - name: APP_ENV
#   value: "production"

envFrom: []
# - secretRef:
#     name: vault-synced-app-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
