---
all:
  children:
    external_alloy_nodes:
      hosts:
        nexus:
          ansible_host: 10.20.139.223
          suffatech_service: nexus
          suffatech_region: virginia

        sonarqube:
          ansible_host: 10.20.141.163
          suffatech_service: sonarqube
          suffatech_region: virginia

        jenkins:
          ansible_host: 10.10.143.109
          suffatech_service: jenkins
          suffatech_region: stockholm

        nginx:
          ansible_host: 10.10.22.57
          suffatech_service: nginx
          suffatech_region: stockholm
