apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: suffatech-ollama
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aykutufk/suffatech.git
    targetRevision: main
    path: deploy/ollama

  destination:
    server: https://kubernetes.default.svc
    namespace: suffatech

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
