apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: suffatech-vault-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aykutufk/suffatech.git
    targetRevision: main
    path: deploy/vault

    # Bu dizinde Chart.yaml veya kustomization.yaml bulunmadığı için
    # ArgoCD dosyaları düz Kubernetes YAML'ları olarak işler.
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: suffatech

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
