fullnameOverride: "bot-server"
replicaCount: 1

image:
  repository: "nexus.suffatech.internal:8083/bot-server"
  tag: "56"

args:
  - "--listen=0.0.0.0:5003"

service:
  type: ClusterIP
  port: 5003
  targetPort: 5003

# Diğer servislere Kubernetes iç IP'lerinden (Cluster DNS) ulaşması için adreslerini veriyoruz
env:
  - name: OLLAMA_BASE_URL
    value: "http://ollama:11434"

  - name: OLLAMA_MODEL
    value: "qwen2.5:3b"

  - name: SCHEMA_SERVICE_URL
    value: "http://schema-server:5001"

  - name: VALUES_SERVICE_URL
    value: "http://values-server:5002"
# AI Modeli API anahtarları gibi sırları VSO üzerinden Vault'tan topluca çekiyoruz
envFrom: []

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi


