fullnameOverride: "schema-server"
replicaCount: 1

image:
  repository: "nexus.suffatech.internal:8083/schema-server"
  tag: "60"

# Spec'te belirtilen argümanlar tanımlandı
args:
  - "--schema-dir=/data/schemas"
  - "--listen=0.0.0.0:5001"

service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

# Pod içinde /data/schemas klasörünü kalıcı diske bağlıyoruz (Persistence)
volumeMounts:
  - name: schema-data
    mountPath: /data/schemas
    readOnly: true

volumes:
  - name: schema-data
    configMap:
      name: schema-server-data

