fullnameOverride: "values-server"
replicaCount: 1

image:
  repository: "nexus.suffatech.internal:8083/values-server"
  tag: "59"

args:
  - "--values-dir=/data/values"
  - "--listen=0.0.0.0:5002"

service:
  type: ClusterIP
  port: 5002
  targetPort: 5002

volumeMounts:
  - name: values-data
    mountPath: /data/values
    readOnly: true

volumes:
  - name: values-data
    configMap:
      name: values-server-data
      