prometheus:
  prometheusSpec:
    nodeSelector:
      role: monitoring

    # Alloy'lardan gelen remote-write isteklerini kabul eder.
    enableRemoteWriteReceiver: true

grafana:
  admin:
    existingSecret: kube-prom-stack-grafana
    userKey: admin-user
    passwordKey: admin-password

  nodeSelector:
    role: monitoring

  dashboards:
    default:
      node-exporter-full:
        gnetId: 1860
        datasource: Prometheus

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      role: monitoring

nodeExporter:
  enabled: false

extraManifests:
  - apiVersion: v1
    kind: Service
    metadata:
      name: prometheus-remote-write
      namespace: monitoring
      labels:
        app.kubernetes.io/name: prometheus-remote-write
        app.kubernetes.io/part-of: kube-prometheus-stack
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
          
      type: NodePort
      externalTrafficPolicy: Cluster

      selector:
        app.kubernetes.io/name: prometheus
        operator.prometheus.io/name: kube-prom-stack-kube-prome-prometheus

      ports:
        - name: remote-write
          protocol: TCP
          port: 9090
          targetPort: 9090
          nodePort: 32001