apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: suffatech
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/part-of: suffatech
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
