apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nexus-pull-secret
  namespace: suffatech
spec:
  type: kv-v2
  mount: secret
  path: suffatech/nexus
  vaultAuthRef: suffatech-vault-auth

  # Vault geçici olarak erişilemezse VSO belirli aralıklarla tekrar dener.
  refreshAfter: 1m

  hmacSecretData: true

  destination:
    create: true
    overwrite: false
    name: nexus-pull-secret
    type: kubernetes.io/dockerconfigjson

    transformation:
      # Vault'taki ham docker-password vb. alanların ayrıca
      # Kubernetes Secret'a kopyalanmasını engeller.
      excludes:
        - ".*"

      templates:
        .dockerconfigjson:
          text: >-
            {"auths":{"{{ index .Secrets "docker-server" }}":{"username":"{{ index .Secrets "docker-username" }}","password":"{{ index .Secrets "docker-password" }}","email":"{{ index .Secrets "docker-email" }}"}}}
